[env:esp32-s3-devkitc-1]
platform = espressif32 @ ^6.8.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

monitor_dtr = 1
monitor_rts = 0

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    m5stack/M5UnitUnified
    m5stack/M5Unit-TOF @ ^0.2.1
    Wire
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.3.0
    adafruit/Adafruit NeoPixel @ ^1.12.0